blog/urls.py
from django.urls import path
from . import views
app_name="blog"
urlpatterns = [
    path("", views.Index.as_view(),name="index"),
    path("<slug:slug>",views.Details.as_view(),name="blogDetail"),
    path("allposts/",views.AllPost.as_view(),name="allPosts"),
    ]

blogProject/urls.py
from django.contrib import admin
from django.urls import path, include   
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("blog.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.urls import reverse
# Create your models here.
class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()

    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return self.full_name()

class Tag(models.Model):
     caption = models.CharField(max_length=20)
     def __str__(self):
         return f'{self.caption}'

class Post(models.Model):
    title = models.CharField(max_length=100)
    exceptText = models.CharField(max_length=200)
    image = models.ImageField(upload_to="posts",null=True)
    date = models.DateField(auto_now=True)
    slug = models.SlugField(unique=True, db_index=True)
    content = models.TextField(validators=[MinLengthValidator(10)])
    author = models.OneToOneField(Author, null=True, on_delete=models.SET_NULL,related_name='fkbooks')
    tag = models.ManyToManyField(Tag)

    def get_absolute_url(self):
        return reverse("blog:blogDetail",args=[self.slug])


    def __str__(self):
        return f'{self.title} {self.exceptText} {self.image} {self.date} {self.slug} {self.content} {self.author} {self.tag} '
    
class Comment(models.Model):
    user_name = models.CharField(max_length=120)
    text = models.TextField(max_length=400)
    email = models.EmailField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")

blog/forms.py
from django import forms
from .models import   Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["user_name","email","text"]
        exclude = ["post"]
        labels = {
            "user_name": "username",
            "email":"email",
            "text":"comment",
        }

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Author, Tag, Comment
from django.http import Http404
from django.views.generic import ListView, DetailView, UpdateView, DeleteView
from django.views import View
from django.http import HttpResponseRedirect
from .forms import CommentForm
from django.urls import reverse

# Create your views here.
# def index(request):
#     posts = Post.objects.all().order_by("-date")[:3]
#     return render(request,"blog/index.html",{"posts":posts})

# def details(request,slug):
#     try:
#         post = Post.objects.get(slug=slug)
#     except:
#         raise Http404()
#     return render(request,"blog/detail.html",{
#         "title": post.title,
#         "exceptText":post.exceptText,
#         "imageName":post.image.url,
#         "date":post.date,
#         "content":post.content,
#         'author':post.author,
#         'tags': post.tag.all(),
#     })

# def allPosts(request):
#     allPost = Post.objects.all().order_by("-date")
#     return render(request,"blog/allPosts.html",{"posts":allPost})

class Index(ListView):
   template_name="blog/index.html"
   model = Post
   context_object_name="posts"
#    ordering= ["-date"]
   def get_queryset(self):
      return Post.objects.all().order_by('-date')[:3]
    #   queryset = super().get_queryset()
    #   data = queryset[:3]
    #   return data
class AllPost(ListView):
    template_name = "blog/allPosts.html"
    model = Post
    context_object_name = "posts"

# class Details(DetailView):
#    template_name = "blog/detail.html"
#    model = Post


class Details(View):

   def get(self,request,slug):
        post = Post.objects.get(slug=slug)
        context = {
            "post" : post,
            "post_tags" : post.tag.all(),
            "comment_form" : CommentForm(),
            "comments" : post.comments.all(),
        }
        return render(request,"blog/detail.html",context)
   
   def post(self, request, slug):
    comment_form = CommentForm(request.POST)  # Corrección de `request.Post` a `request.POST`
    post = get_object_or_404(Post,slug=slug)  # `get_object_or_404` es mejor para manejar errores

    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.post = post
        comment.save()
        return HttpResponseRedirect(reverse("blog:blogDetail", args=[slug]))

    context = {
        "post": post,
        "post_tags": post.tag.all(),
        "comment_form": CommentForm(),  # Si hay errores, se muestra un formulario vacío
        "comments": post.comments.all()  # Se corrigió el error de sintaxis aquí
    }

    return render(request, "blog/detail.html", context)

blog/templates/blog/allPosts.html
{% extends "blog/base.html" %}
{% load static %}
{% block title %}
    All blogs
{% endblock %}
{% block content %}
    {% include "blog/includes/post.html" %}
    <button><a href="{% url 'blog:index' %}">Posts page</a></button>
{% endblock %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

blog/templates/blog/detail.html
{% extends "blog/base.html" %} {% load static %} {% block title %} {{ title }}
{% endblock %} {% block content %}
<h1>{{ post.title }}</h1>
<h2>Author: {{ post.author }}</h2>
<img src="{{ post.image.url }}" alt="imageName" />
<p>{{ post.exceptText }}</p>
<p>{{ post.date }}</p>
<p>{{ post.content }}</p>
Tags: {% for tag in post.tags %}
<p>{{ tag.caption }}</p>
{% endfor %}
<h3>To send an email to the author:</h3>
<section>
  <ul>
    {% for comment in comments %}
    <li>
      <h2>{{ comment.user_name}}</h2>
      <p>{{ comment.text|linebreaks }}</p>
    </li>
    {% endfor %}
  </ul>

  <h3>Leave a comment:</h3>
  <form method="POST">
    {% csrf_token %} 
    {{ comment_form.as_p }}
    <button type="submit">Submit Comment</button>
  </form>
</section>
<a href="{{ post.author.email }}">{{ post.author.email }}</a>
<button><a href="{% url 'blog:index' %}">Posts page</a></button>
{% endblock %}

blog/templates/blog/includes/post.html
{% extends "blog/base.html" %}
{% load static %}
{% block title %}
    All blogs
{% endblock %}
{% block content %}
    <img src="{% static 'images/descarga.png' %}" alt="ImagenPrincipal" width="100px" height="100px">
    <ul>
        {% for post in posts %}
            <li><img src="{{ post.image.url }}" alt=""> <h1><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h1>
                <p>{{ post.date|date:"D d-M-Y" }}</p>
              <p>  {{ post.exceptText }}</p>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

blog/templates/blog/index.html
{% extends "blog/base.html" %}
{% load static %}
{% block title %}
    All blogs
{% endblock %}
{% block content %}
    <img src="{% static 'images/descarga.png' %}" alt="ImagenPrincipal" width="100px" height="100px">
    <ul>
        {% for post in posts %}
            <li><img src="{{ post.image.url }}" alt=""> <h1><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h1>
                <p>{{ post.date|date:"D d-M-Y" }}</p>
              <p>  {{ post.exceptText }}</p>
            </li>
        {% endfor %}
    </ul>
    <a href="{% url 'blog:allPosts' %}">All Posts</a>
{% endblock %}